[package]
name = "textdistance"
version = "0.1.6"
edition = "2021"
description = "Rust library for approximate string matching"
license-file = "LICENSE"
repository = "https://github.com/pluots/stringmetrics-rust"
# This won't auto link for some reason, no harm in having it manual
documentation = "https://docs.rs/stringmetrics"


[dependencies]
# itertools = "0.10.3"


[dev-dependencies]
# more-asserts = "0.2.2"
