[package]
name = "stringmetrics"
version = "0.1.12"
edition = "2021"
description = "Rust library for approximate string matching"
license-file = "LICENSE"
repository = "https://github.com/pluots/stringmetrics-rust"
# This won't auto link for some reason, no harm in having it manual
documentation = "https://docs.rs/stringmetrics"


[dependencies]
# itertools = "0.10.3"


[dev-dependencies]
# more-asserts = "0.2.2"

[package.metadata.docs.rs]
rustdoc-args = [
    "--html-in-header",
    ".cargo/registry/src/github.com-1ecc6299db9ec823/katex-doc-0.1.0/katex.html",
]
