[package]
name = "textdistance"
version = "0.1.4"
edition = "2021"
description = "Rust library for approximate string matching"
license-file = "LICENSE"
repository = "https://github.com/pluots/textdistance-rust"
# This won't auto link for some reason, no harm in having it manual
documentation = "https://docs.rs/textdistance"


[dependencies]
itertools = "0.10.3"


[dev-dependencies]
more-asserts = "0.2.2"
