[package]
name = "stringmetrics_profiling"
version = "2.1.1"
edition = "2021"
publish = false

[dependencies]
stringmetrics = { path = "../stringmetrics" }

[[bin]]
name = "prof_lev"
path = "src/lev.rs"
